default_context:
  project_name: 'Bemonex'
  project_slug: 'bemonex'
  domain_main: 'bemonex.online'
  domain_staging: 'stag.bemonex.online'
  docker_swarm_stack_name_main: 'bemonex-online'
  docker_swarm_stack_name_staging: 'stag-bemonex-online'
  secret_key: '1'
  first_superuser: 'www'
  first_superuser_password: 'www'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.bemonex.online", "https://stag.bemonex.online", "https://bemonex.online", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: 'www'
  smtp_password: 'www'
  smtp_emails_from_email: 'info@bemonex.online'
  postgres_password: 'www'
  pgadmin_default_user: 'www'
  pgadmin_default_user_password: 'www'
  traefik_constraint_tag: 'www'
  traefik_constraint_tag_staging: 'www'
  traefik_public_constraint_tag: 'www'
  flower_auth: 'www'
  sentry_dsn: 'www'
  docker_image_prefix: 'www'
  docker_image_backend: 'wwwbackend'
  docker_image_celeryworker: 'wwwceleryworker'
  docker_image_frontend: 'wwwfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
